// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortTrackingSystem.Core.Data;

#nullable disable

namespace PortTrackingSystem.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831135800_FixCrewMemberFirstNameAndOptionalContact")]
    partial class FixCrewMemberFirstNameAndOptionalContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Cargoes", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightTon")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CargoId");

                    b.HasIndex("ShipId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.CrewMembers", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrewId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Port", b =>
                {
                    b.Property<int>("PortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipId"));

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("ShipId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.ShipCrewAssignments", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CrewId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipCrewAssignments");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.ShipVisits", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("PortId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipVisits");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Cargoes", b =>
                {
                    b.HasOne("PortTrackingSystem.Core.Entities.Ship", "Ship")
                        .WithMany("Cargoes")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.ShipCrewAssignments", b =>
                {
                    b.HasOne("PortTrackingSystem.Core.Entities.CrewMembers", "CrewMember")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortTrackingSystem.Core.Entities.Ship", "Ship")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.ShipVisits", b =>
                {
                    b.HasOne("PortTrackingSystem.Core.Entities.Port", null)
                        .WithMany("ShipVisits")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortTrackingSystem.Core.Entities.Ship", null)
                        .WithMany("ShipVisits")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.CrewMembers", b =>
                {
                    b.Navigation("CrewAssignments");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Port", b =>
                {
                    b.Navigation("ShipVisits");
                });

            modelBuilder.Entity("PortTrackingSystem.Core.Entities.Ship", b =>
                {
                    b.Navigation("Cargoes");

                    b.Navigation("CrewAssignments");

                    b.Navigation("ShipVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
